name: as_dock
channels:
  - pytorch
  - nvidia
  - conda-forge
  - dglteam
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - tqdm
  - requests
  - networkx
  - tabulate
  - psutil
  - yacs
  - statsmodels
  - biopython
  - rdkit
  - pytorch
  - pytorch-cuda=12.4
  - pytorch-geometric=2.6.1
  - dgl=2.1.0
  - fvcore
  - iopath
  - pip:
      - pytorch-lightning>=2.2
      - torchmetrics
      - tensorboard
      - pathlib2
